version: '3'

services:
  server:
    image: registry.gitlab.com/compliancedb/compliancedb/server
    volumes:
    - cdb_data:/cdb_data

  hub:
    ports:
      - "80:80"
    image: registry.gitlab.com/compliancedb/compliancedb/nginx

  web:
    image: registry.gitlab.com/compliancedb/compliancedb/web
    environment:
    - IS_ON_PREM=TRUE

volumes:
  cdb_data:


